[program:rivo-bot]
command=/opt/nodejs18/bin/node index.js
directory=/home/revo/RIVO_bot
autostart=true
autorestart=true
stderr_logfile=/tmp/rivo_err.log
stdout_logfile=/tmp/rivo_out.log
environment=NODE_ENV=production
